In [2]:
import numpy as np;

In [15]:
a = np.array([1, 2, 3,4],dtype='complex');
print(a);
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)


[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
1
4
(4,)
complex128
16
64


In [21]:
np.zeros((3,3),dtype='int')
np.ones((3,3),dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
np.arange(1,5)

array([1, 2, 3, 4])

In [25]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [33]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a.min()

np.int64(1)

In [38]:
a.sum()

np.int64(45)

In [41]:
a.sum(axis=1)

array([ 6, 15, 24])

In [43]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [45]:
np.std(a)

np.float64(2.581988897471611)

In [49]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a+b # shapes should be same

array([[ 6,  8],
       [10, 12]])

In [56]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [53]:
a*b

array([[ 5, 12],
       [21, 32]])

In [54]:
a.dot(b)

array([[19, 22],
       [43, 50]])