In [140]:
print("radha")

radha


**why it is used**


let's say that the model is trained on some training set and now the model is get some unexpected data for test so now it will perform badly so cross validation is used to check how the model respond on the unexpected data.


In [141]:
import numpy as np;
import pandas as pd;
from sklearn.datasets import load_digits;


In [142]:
digits = load_digits();


In [143]:
from sklearn.model_selection import train_test_split;
X_train , X_test , y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.4)

In [144]:
from sklearn.linear_model import LogisticRegression;
model = LogisticRegression()
model.fit(X_train , y_train)
round(model.score(X_test,y_test)*100,2)


c:\Users\AMAN CHOUDHARY\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


96.52

In [145]:
from sklearn.svm import SVC
model = SVC();
model.fit(X_train,y_train);
round(model.score(X_test,y_test)*100,2)


98.75

In [146]:
from sklearn.ensemble import RandomForestClassifier;
model = RandomForestClassifier();
model.fit(X_train,y_train)
round(model.score(X_test,y_test)*100,2)

97.5

The entire dataset is split into k equally sized "folds."
In each iteration, one fold is designated as the test set, and the remaining k-1 folds are combined to form the training set.


kf.split(data) splits the data indices into training and test sets for each fold.

In [147]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3);
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [148]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index,test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [149]:
def get_score(model,X_train,y_train , X_test,y_test):
    model.fit(X_train,y_train)
    return round(model.score(X_test,y_test)*100,2);

In [150]:
print(get_score(RandomForestClassifier(),X_train,y_train,X_test,y_test))

97.22


In [151]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [152]:
scores_lor = []
scores_rf = []
scores_svm = []

In [153]:
for train_index , test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index], digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_lor.append(get_score(LogisticRegression(),X_train,y_train,X_test,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50),X_train,y_train,X_test,y_test))
    scores_svm.append(get_score(SVC(),X_train,y_train,X_test,y_test))
    

c:\Users\AMAN CHOUDHARY\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\AMAN CHOUDHARY\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:

In [154]:
scores_lor

[92.32, 94.16, 91.49]

In [155]:
print(np.average(scores_rf))
print(np.average(scores_lor))
print(np.average(scores_svm))
# hence use svm

94.32333333333332
92.65666666666665
96.77


In [156]:
from sklearn.model_selection import cross_val_score

In [158]:
score = cross_val_score(LogisticRegression(),digits.data,digits.target)
score

c:\Users\AMAN CHOUDHARY\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\AMAN CHOUDHARY\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [159]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [162]:
np.average(cross_val_score(RandomForestClassifier(),digits.data,digits.target))*100

np.float64(94.04859176725472)